// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

package handlers

import (
	pb "trss"
)

// TimedTask implements Service.
func TimedTask(StartTimedTask int32, EndTimedTask int32, RestallTimedTask int32) (*pb.TimedTaskRequest, error) {
	request := pb.TimedTaskRequest{
		Start:   StartTimedTask,
		End:     EndTimedTask,
		Restall: RestallTimedTask,
	}
	return &request, nil
}

// TimedTaskTime implements Service.
func TimedTaskTime(StartTimedTaskTime int32, EndTimedTaskTime int32, RestallTimedTaskTime int32) (*pb.TimedTaskRequest, error) {
	request := pb.TimedTaskRequest{
		Start:   StartTimedTaskTime,
		End:     EndTimedTaskTime,
		Restall: RestallTimedTaskTime,
	}
	return &request, nil
}
