// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

package svc

// This file provides server-side bindings for the gRPC transport.
// It utilizes the transport/grpc.Server.

import (
	"context"
	"net/http"

	"google.golang.org/grpc/metadata"

	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "trss"
)

// MakeGRPCServer makes a set of endpoints available as a gRPC TimServiceServer.
func MakeGRPCServer(endpoints Endpoints) pb.TimServiceServer {
	serverOptions := []grpctransport.ServerOption{
		grpctransport.ServerBefore(metadataToContext),
	}
	return &grpcServer{
		// timservice

		timedtask: grpctransport.NewServer(
			endpoints.TimedTaskEndpoint,
			DecodeGRPCTimedTaskRequest,
			EncodeGRPCTimedTaskResponse,
			serverOptions...,
		),
		timedtasktime: grpctransport.NewServer(
			endpoints.TimedTaskTimeEndpoint,
			DecodeGRPCTimedTaskTimeRequest,
			EncodeGRPCTimedTaskTimeResponse,
			serverOptions...,
		),
	}
}

// grpcServer implements the TimServiceServer interface
type grpcServer struct {
	timedtask     grpctransport.Handler
	timedtasktime grpctransport.Handler
}

// Methods for grpcServer to implement TimServiceServer interface

func (s *grpcServer) TimedTask(ctx context.Context, req *pb.TimedTaskRequest) (*pb.TimedTaskResponse, error) {
	_, rep, err := s.timedtask.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.TimedTaskResponse), nil
}

func (s *grpcServer) TimedTaskTime(ctx context.Context, req *pb.TimedTaskRequest) (*pb.TimedTaskResponse, error) {
	_, rep, err := s.timedtasktime.ServeGRPC(ctx, req)
	if err != nil {
		return nil, err
	}
	return rep.(*pb.TimedTaskResponse), nil
}

// Server Decode

// DecodeGRPCTimedTaskRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC timedtask request to a user-domain timedtask request. Primarily useful in a server.
func DecodeGRPCTimedTaskRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.TimedTaskRequest)
	return req, nil
}

// DecodeGRPCTimedTaskTimeRequest is a transport/grpc.DecodeRequestFunc that converts a
// gRPC timedtasktime request to a user-domain timedtasktime request. Primarily useful in a server.
func DecodeGRPCTimedTaskTimeRequest(_ context.Context, grpcReq interface{}) (interface{}, error) {
	req := grpcReq.(*pb.TimedTaskRequest)
	return req, nil
}

// Server Encode

// EncodeGRPCTimedTaskResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain timedtask response to a gRPC timedtask reply. Primarily useful in a server.
func EncodeGRPCTimedTaskResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.TimedTaskResponse)
	return resp, nil
}

// EncodeGRPCTimedTaskTimeResponse is a transport/grpc.EncodeResponseFunc that converts a
// user-domain timedtasktime response to a gRPC timedtasktime reply. Primarily useful in a server.
func EncodeGRPCTimedTaskTimeResponse(_ context.Context, response interface{}) (interface{}, error) {
	resp := response.(*pb.TimedTaskResponse)
	return resp, nil
}

// Helpers

func metadataToContext(ctx context.Context, md metadata.MD) context.Context {
	for k, v := range md {
		if v != nil {
			// The key is added both in metadata format (k) which is all lower
			// and the http.CanonicalHeaderKey of the key so that it can be
			// accessed in either format
			ctx = context.WithValue(ctx, k, v[0])
			ctx = context.WithValue(ctx, http.CanonicalHeaderKey(k), v[0])
		}
	}

	return ctx
}
