// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 7dc4d5d85c
// Version Date: Mon May 28 22:12:59 UTC 2018

// Package grpc provides a gRPC client for the TimService service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "trss"
	"trss/timservice-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.TimServiceServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var timedtaskEndpoint endpoint.Endpoint
	{
		timedtaskEndpoint = grpctransport.NewClient(
			conn,
			"echo.TimService",
			"TimedTask",
			EncodeGRPCTimedTaskRequest,
			DecodeGRPCTimedTaskResponse,
			pb.TimedTaskResponse{},
			clientOptions...,
		).Endpoint()
	}

	var timedtasktimeEndpoint endpoint.Endpoint
	{
		timedtasktimeEndpoint = grpctransport.NewClient(
			conn,
			"echo.TimService",
			"TimedTaskTime",
			EncodeGRPCTimedTaskTimeRequest,
			DecodeGRPCTimedTaskTimeResponse,
			pb.TimedTaskResponse{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		TimedTaskEndpoint:     timedtaskEndpoint,
		TimedTaskTimeEndpoint: timedtasktimeEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCTimedTaskResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC timedtask reply to a user-domain timedtask response. Primarily useful in a client.
func DecodeGRPCTimedTaskResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.TimedTaskResponse)
	return reply, nil
}

// DecodeGRPCTimedTaskTimeResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC timedtasktime reply to a user-domain timedtasktime response. Primarily useful in a client.
func DecodeGRPCTimedTaskTimeResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.TimedTaskResponse)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCTimedTaskRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain timedtask request to a gRPC timedtask request. Primarily useful in a client.
func EncodeGRPCTimedTaskRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.TimedTaskRequest)
	return req, nil
}

// EncodeGRPCTimedTaskTimeRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain timedtasktime request to a gRPC timedtasktime request. Primarily useful in a client.
func EncodeGRPCTimedTaskTimeRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.TimedTaskRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
